name: Fetch Events
on:
  schedule:
     - cron: "*/5 * * * *" 
  workflow_dispatch: # allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Fetch API data
        run: |
          curl -s "${{ secrets.API_URL }}" -o data.json
          curl -s "${{ secrets.SPORTS_API_URL }}" -o sports.json
          
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Update events data - $(date)"
          git push
